export const LOAD_COMPANY = 'LOAD_COMPANY';
export const LOAD_COMPANY_COMPLETED = 'LOAD_COMPANY_COMPLETED';
export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CREATE_LETTER = 'CREATE_LETTER';
export const CREATE_LETTER_COMPLETED = 'CREATE_LETTER_COMPLETED';
export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
