export const CHANGE_INPUT = 'CHANGE_INPUT';
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const SUBMIT_LOGIN_COMPLETED = 'SUBMIT_LOGIN_COMPLETED';
export const SUBMIT_LOGIN_ERROR = 'SUBMIT_LOGIN_ERROR';